export const PALETTE = [
  '#3b82f6', // blue-500
  '#10b981', // emerald-500
  '#f59e0b', // amber-500
  '#ef4444', // red-500
  '#8b5cf6', // violet-500
  '#ec4899', // pink-500
  '#06b6d4', // cyan-500
  '#f97316', // orange-500
  '#84cc16', // lime-500
  '#6366f1', // indigo-500
  '#a855f7', // purple-500
  '#d946ef', // fuchsia-500
  '#14b8a6', // teal-500
  '#0ea5e9', // sky-500
];

export const DICT = {
  es: {
    upload_title: "Pura Vida Analytics",
    upload_sub: "Sube el archivo Excel (.xlsx) o CSV de la Base de Datos Pura Vida para procesar los retornos.",
    upload_btn: "Cargar Excel o CSV",
    processing: "Procesando archivo...",
    upload_help: "El sistema detectará automáticamente cajas pendientes de liquidación y protegerá los promedios.",
    dash_title: "Dashboard Comercial: Wholesalers",
    dash_sub: "Comparativa de Retorno estandarizada",
    load_other: "Cargar otro archivo",
    filters: "Filtros Generales",
    vessel: "Nave",
    variety: "Variedad",
    format: "Filtro Formato Físico (Kg)",
    all_f: "Todos los formatos",
    all: "Todas",
    view_by: "Visualizar Resultados Por",
    kilo: "Kilo",
    box_eq: "Caja Equivalente",
    weight_eq: "Peso Caja Equivalente (Kg)",
    vol_analyzed: "Volumen Analizado",
    phys_boxes: "Cajas Físicas",
    best_gross: "Mejor Venta Bruta",
    best_fob: "Mejor FOB Neto",
    weighted_global: "Ponderado global",
    tab_ranking: "🏆 Ranking Global",
    tab_usd: "🚢 FOB Neto",
    tab_rmb: "💰 Venta Bruta",
    tab_vol: "📦 Participación",
    tab_h2h: "🥊 Head-to-Head",
    tab_breakdown: "👤 Resumen Recibidor",
    no_data: "No hay datos disponibles.",
    rank_by: "Rankear por:",
    rank_market: "📈 Rendimiento vs Mercado (El más justo)",
    rank_usd: "💲 FOB Neto",
    rank_rmb: "💴 Venta Bruta",
    rank_vol: "📦 Volumen",
    rank_alert: "El Rendimiento vs Mercado es la métrica más precisa. Evalúa la mezcla exacta de fruta (calibre, variedad, nave y formato) que recibió cada importador y compara sus retornos con el promedio de todos los demás que recibieron esa misma fruta. Esto elimina la injusticia de comparar a un recibidor que recibió calibres pequeños con otro que recibió Jumbos.",
    rest_ranking: "Resto del Ranking",
    h2h_perf: "DESEMPEÑO PONDERADO",
    h2h_results: "RESULTADO DEL EJERCICIO",
    h2h_total_real: "Total Real",
    h2h_adjusted: "Ajustado (Volumen Equitativo)",
    h2h_diff_unit: "DIFERENCIA FOB POR CAJA EQUIVALENTE 5KG (USD)",
    h2h_diff_total: "DIFERENCIA FOB TOTAL (USD)",
    h2h_favor: "A favor de",
    h2h_chart: "COMPARATIVA POR CALIBRE (FOB USD)",
    tie: "EMPATE",
    breakdown_analyze: "Recibidor a Analizar:",
    breakdown_alert: "que aún no tienen precio de liquidación. Estos volúmenes fueron contabilizados en los totales, pero excluidos del cálculo de promedios.",
    vol_exp: "Volumen Exportado",
    gross_sale_total: "Venta Bruta Total",
    prom: "Prom",
    dest_cost: "Costo Destino (RMB)",
    pct_sale: "de la Vta Bruta",
    fob_gen: "FOB Neto Generado",
    cost_breakdown: "Desglose de Costos en Destino (RMB)",
    comissions: "Comisiones",
    freight: "Costo de Flete",
    vat: "VAT (Impuestos)",
    others: "Otros Costos",
    perf_vs_market: "Desempeño por Contenedor vs Promedio Mercado",
    cont: "Contenedor",
    date: "Nave / Fecha",
    producers: "Productores",
    sale: "Venta",
    market: "Mercado",
    diff: "Dif vs Mercado",
    to_be_priced: "Por fijar",
    dist_vol: "Distribución de Volumen",
    language: "Idioma",
    download_pdf: "Descargar PDF",
    selected_items: "seleccionadas",
    applied_filters: "Filtros aplicados",
    h2h_vol_chart: "Comparativa de Volumen por Calibre",
    h2h_principal_a: "PRINCIPAL (A)",
    h2h_compare_b: "COMPARAR CON (B)",
    h2h_metric: "MÉTRICA",
    h2h_adjusted_help: "Calculado usando el volumen del recibidor menor",
    h2h_real_help: "Calculado usando el volumen real del recibidor B",
    h2h_vs: "vs"
  },
  en: {
    upload_title: "Pura Vida Analytics",
    upload_sub: "Upload the Pura Vida Database Excel (.xlsx) or CSV file to process returns.",
    upload_btn: "Upload Excel or CSV",
    processing: "Processing file...",
    upload_help: "The system automatically detects unpriced boxes and protects averages.",
    dash_title: "Commercial Dashboard: Wholesalers",
    dash_sub: "Standardized Return Comparison",
    load_other: "Load another file",
    filters: "General Filters",
    vessel: "Vessel",
    variety: "Variety",
    format: "Physical Format (Kg)",
    all_f: "All formats",
    all: "All",
    view_by: "View Results By",
    kilo: "Kilo",
    box_eq: "Equivalent Box",
    weight_eq: "Equivalent Box Weight (Kg)",
    vol_analyzed: "Analyzed Volume",
    phys_boxes: "Physical Boxes",
    best_gross: "Best Gross Sales",
    best_fob: "Best Net FOB",
    weighted_global: "Global weighted",
    tab_ranking: "🏆 Global Ranking",
    tab_usd: "🚢 Net FOB",
    tab_rmb: "💰 Gross Sales",
    tab_vol: "📦 Volume Share",
    tab_h2h: "🥊 Head-to-Head",
    tab_breakdown: "👤 Receiver Summary",
    no_data: "No data available.",
    rank_by: "Rank by:",
    rank_market: "📈 Performance vs Market (Fairest)",
    rank_usd: "💲 Net FOB",
    rank_rmb: "💴 Gross Sales",
    rank_vol: "📦 Volume",
    rank_alert: "Performance vs Market is the most precise metric. It evaluates the exact mix of fruit (size, variety, vessel, and format) received by each importer and compares their returns with the average of everyone else who received that exact same fruit. This eliminates the unfairness of comparing an importer who received small sizes with one who received Jumbos.",
    rest_ranking: "Rest of Ranking",
    h2h_perf: "WEIGHTED PERFORMANCE",
    h2h_results: "RESULT OF THE EXERCISE",
    h2h_total_real: "Total Real",
    h2h_adjusted: "Adjusted (Equitable Volume)",
    h2h_diff_unit: "FOB DIFFERENCE PER EQUIVALENT 5KG BOX (USD)",
    h2h_diff_total: "TOTAL FOB DIFFERENCE (USD)",
    h2h_favor: "In favor of",
    h2h_chart: "COMPARISON BY SIZE (FOB USD)",
    tie: "TIE",
    breakdown_analyze: "Receiver to Analyze:",
    breakdown_alert: "that do not yet have a settlement price. These volumes were counted in the totals, but excluded from average calculations.",
    vol_exp: "Exported Volume",
    gross_sale_total: "Total Gross Sales",
    prom: "Avg",
    dest_cost: "Destination Cost (RMB)",
    pct_sale: "of Gross Sales",
    fob_gen: "Generated Net FOB",
    cost_breakdown: "Destination Costs Breakdown (RMB)",
    comissions: "Commissions",
    freight: "Freight Costs",
    vat: "VAT (Taxes)",
    others: "Other Costs",
    perf_vs_market: "Performance by Container vs Market Average",
    cont: "Container",
    date: "Vessel / Date",
    producers: "Producers",
    sale: "Sales",
    market: "Market",
    diff: "Diff vs Market",
    to_be_priced: "To be priced",
    dist_vol: "Volume Distribution",
    language: "Language",
    download_pdf: "Download PDF",
    selected_items: "selected",
    applied_filters: "Applied filters",
    h2h_vol_chart: "Volume Comparison by Size",
    h2h_principal_a: "PRINCIPAL (A)",
    h2h_compare_b: "COMPARE WITH (B)",
    h2h_metric: "METRIC",
    h2h_adjusted_help: "Calculated using the volume of the smaller receiver",
    h2h_real_help: "Calculated using the real volume of receiver B",
    h2h_vs: "vs"
  }
};
