export const VALID_CLIENTS = ['HUASHENG', 'YUHUA', 'FRUIT MATE', 'SANGO', 'HATTAT', 'PARAMOUNT', 'JOY WING MAU'];

export const COLORS = {
  'HUASHENG': '#3b82f6',
  'YUHUA': '#10b981',
  'FRUIT MATE': '#f59e0b',
  'SANGO': '#ef4444',
  'HATTAT': '#8b5cf6',
  'PARAMOUNT': '#ec4899',
  'JOY WING MAU': '#06b6d4'
};

export const DICT = {
  es: {
    upload_title: "Pura Vida Analytics",
    upload_sub: "Sube el archivo Excel (.xlsx) o CSV de la Base de Datos Pura Vida para procesar los retornos.",
    upload_btn: "Cargar Excel o CSV",
    processing: "Procesando archivo...",
    upload_help: "El sistema detectará automáticamente cajas pendientes de liquidación y protegerá los promedios.",
    dash_title: "Dashboard Comercial: Wholesalers",
    dash_sub: "Comparativa de Retorno estandarizada",
    load_other: "Cargar otro archivo",
    filters: "Filtros Generales",
    vessel: "Nave",
    variety: "Variedad",
    format: "Filtro Formato Físico (Kg)",
    all_f: "Todos los formatos",
    all: "Todas",
    view_by: "Visualizar Resultados Por",
    kilo: "Kilo",
    box_eq: "Caja Equivalente",
    weight_eq: "Peso Caja Equivalente (Kg)",
    vol_analyzed: "Volumen Analizado",
    phys_boxes: "Cajas Físicas",
    best_gross: "Mejor Venta Bruta",
    best_fob: "Mejor FOB Neto",
    weighted_global: "Ponderado global",
    tab_ranking: "🏆 Ranking Global",
    tab_usd: "🚢 FOB Neto",
    tab_rmb: "💰 Venta Bruta",
    tab_vol: "📦 Participación",
    tab_h2h: "🥊 Head-to-Head",
    tab_breakdown: "👤 Resumen Recibidor",
    no_data: "No hay datos disponibles.",
    rank_by: "Rankear por:",
    rank_market: "📈 Rendimiento vs Mercado (El más justo)",
    rank_usd: "💲 FOB Neto",
    rank_rmb: "💴 Venta Bruta",
    rank_vol: "📦 Volumen",
    rank_alert: "El Rendimiento vs Mercado es la métrica más precisa. Evalúa la mezcla exacta de fruta (calibre, variedad, nave y formato) que recibió cada importador y compara sus retornos con el promedio de todos los demás que recibieron esa misma fruta. Esto elimina la injusticia de comparar a un recibidor que recibió calibres pequeños con otro que recibió Jumbos.",
    rest_ranking: "Resto del Ranking",
    h2h_perf: "Desempeño Ponderado",
    h2h_results: "Resultado del Ejercicio",
    h2h_total_real: "Total Real",
    h2h_adjusted: "Ajustado (Volumen Equitativo)",
    h2h_diff_exact: "Diferencia Exacta a Favor de la Exportadora",
    h2h_diff_unit: "Diferencia FOB por",
    h2h_diff_total: "Diferencia FOB Total (USD)",
    h2h_favor: "A favor de",
    h2h_chart: "Comparativa por Calibre (FOB USD)",
    h2h_vol_chart: "Comparativa de Volumen por Calibre",
    h2h_principal_a: "PRINCIPAL (A)",
    h2h_compare_b: "COMPARAR CON (B)",
    h2h_vs: "vs",
    tie: "Empate",
    breakdown_analyze: "Recibidor a Analizar:",
    breakdown_alert: "que aún no tienen precio de liquidación. Estos volúmenes fueron contabilizados en los totales, pero excluidos del cálculo de promedios.",
    vol_exp: "Volumen Exportado",
    gross_sale_total: "Venta Bruta Total",
    prom: "Prom",
    dest_cost: "Costo Destino (RMB)",
    pct_sale: "de la Vta Bruta",
    fob_gen: "FOB Neto Generado",
    cost_breakdown: "Desglose de Costos en Destino (RMB)",
    comissions: "Comisiones",
    freight: "Flete Interno",
    vat: "VAT (Impuestos)",
    others: "Otros Costos",
    perf_vs_market: "Desempeño por Contenedor vs Promedio Mercado",
    cont: "Contenedor",
    date: "Nave / Fecha",
    producers: "Productores",
    sale: "Venta",
    market: "Mercado",
    diff: "Dif vs Mercado",
    to_be_priced: "Por fijar",
    dist_vol: "Distribución de Volumen",
    language: "Idioma",
    download_pdf: "Descargar PDF",
    selected_items: "seleccionadas",
    applied_filters: "Filtros aplicados"
  },
  en: {
    upload_title: "Pura Vida Analytics",
    upload_sub: "Upload the Pura Vida Database Excel (.xlsx) or CSV file to process returns.",
    upload_btn: "Upload Excel or CSV",
    processing: "Processing file...",
    upload_help: "The system automatically detects unpriced boxes and protects averages.",
    dash_title: "Commercial Dashboard: Wholesalers",
    dash_sub: "Standardized Return Comparison",
    load_other: "Load another file",
    filters: "General Filters",
    vessel: "Vessel",
    variety: "Variety",
    format: "Physical Format (Kg)",
    all_f: "All formats",
    all: "All",
    view_by: "View Results By",
    kilo: "Kilo",
    box_eq: "Equivalent Box",
    weight_eq: "Equivalent Box Weight (Kg)",
    vol_analyzed: "Analyzed Volume",
    phys_boxes: "Physical Boxes",
    best_gross: "Best Gross Sales",
    best_fob: "Best Net FOB",
    weighted_global: "Global weighted",
    tab_ranking: "🏆 Global Ranking",
    tab_usd: "🚢 Net FOB",
    tab_rmb: "💰 Gross Sales",
    tab_vol: "📦 Volume Share",
    tab_h2h: "🥊 Head-to-Head",
    tab_breakdown: "👤 Receiver Summary",
    no_data: "No data available.",
    rank_by: "Rank by:",
    rank_market: "📈 Perf. vs Market (Fairest)",
    rank_usd: "💲 Net FOB",
    rank_rmb: "💴 Gross Sales",
    rank_vol: "📦 Volume",
    rank_alert: "Performance vs Market is the most precise metric. It evaluates the exact mix of fruit (size, variety, vessel, and format) received by each importer and compares their returns with the average of everyone else who received that exact same fruit. This eliminates the unfairness of comparing an importer who received small sizes with one who received Jumbos.",
    rest_ranking: "Rest of Ranking",
    h2h_perf: "Weighted Performance",
    h2h_results: "Exercise Result",
    h2h_total_real: "Total Real",
    h2h_adjusted: "Adjusted (Equitable Volume)",
    h2h_diff_exact: "Exact Difference in Favor of Exporter",
    h2h_diff_unit: "FOB Difference per",
    h2h_diff_total: "Total FOB Difference (USD)",
    h2h_favor: "In favor of",
    h2h_chart: "Comparison by Size (FOB USD)",
    h2h_vol_chart: "Volume Comparison by Size",
    h2h_principal_a: "PRINCIPAL (A)",
    h2h_compare_b: "COMPARE WITH (B)",
    h2h_vs: "vs",
    tie: "Tie",
    breakdown_analyze: "Receiver to Analyze:",
    breakdown_alert: "that do not yet have a settlement price. These volumes were counted in the totals, but excluded from average calculations.",
    vol_exp: "Exported Volume",
    gross_sale_total: "Total Gross Sales",
    prom: "Avg",
    dest_cost: "Destination Cost (RMB)",
    pct_sale: "of Gross Sales",
    fob_gen: "Generated Net FOB",
    cost_breakdown: "Destination Costs Breakdown (RMB)",
    comissions: "Commissions",
    freight: "Inland Freight",
    vat: "VAT (Taxes)",
    others: "Other Costs",
    perf_vs_market: "Performance by Container vs Market Average",
    cont: "Container",
    date: "Vessel / Date",
    producers: "Producers",
    sale: "Sales",
    market: "Market",
    diff: "Diff vs Market",
    to_be_priced: "To be priced",
    dist_vol: "Volume Distribution",
    language: "Language",
    download_pdf: "Download PDF",
    selected_items: "selected",
    applied_filters: "Applied filters"
  }
};
